server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ecommerce"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: "VfSv+WcFQhGnYTf6hVqq9BsJkQdmXe4B0E8VNeI8RgTclWaWy6vCugd7zOUkK6lYOI6O1DGfi1IedFAIMXA3cQ=="
  algorithm: "HS512"
  expiration: 86400000